#!/bin/sh

FIFO="/tmp/dvtmp-status.$$"

[ -p "$FIFO" ] || mkfifo -m 600 "$FIFO" || exit 1

while true; do
	date +%H:%M
	sleep 60
done > "$FIFO" &

STATUS_PID=$!
dvtmp -s "$FIFO" "$@" 2> /dev/null
kill $STATUS_PID
wait $STATUS_PID 2> /dev/null
rm -f "$FIFO"
